# Generated by Django 3.1 on 2020-08-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='atracao',
            field=models.ManyToManyField(to='atracoes.Atracao'),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
