# Generated by Django 3.1 on 2020-08-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha1', models.CharField(max_length=168)),
                ('linha2', models.CharField(blank=True, max_length=168, null=True)),
                ('cidade', models.CharField(max_length=168)),
                ('estado', models.CharField(max_length=64)),
                ('pais', models.CharField(max_length=64)),
                ('latitude', models.IntegerField(blank=True, null=True)),
                ('longitude', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
